name: Appsero E2E Tests
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 30  # Reduce the timeout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps
      - name: Run Playwright tests with verbose logging and retries
        run: DEBUG=pw:api npx playwright test --retries=1 --workers=1
        env:
          CI: true
          USER_NAME: ${{ secrets.USER_NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PRODUCTION_URL: ${{ secrets.PRODUCTION_URL }}
          STAGING_URL: ${{ secrets.STAGING_URL }}
          STAGING: ${{ secrets.STAGING }}
          PRODUCTION_SITE: ${{ secrets.PRODUCTION_SITE }}
          STAGING_SITE: ${{ secrets.STAGING_SITE }}
      - name: Save Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
      - name: Send Test Report on email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}. This test is conducted on Appsero Staging site. The attached index.html file will give the details report.
          to: saif@wedevs.com,farazi@wedevs.com,tons2468@gmail.com
          from: rubaiyat.mohammad@wedevs.com
          attachments: ./playwright-report/index.html